//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 05:38:27 PM BST 
//

package eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.ack;

import eu.europa.ema.phv.common.xmladapter.IcsrR2DateAdapter;
import org.eclipse.persistence.oxm.annotations.XmlPath;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.util.Date;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "ichicsrmessageheader")
public class IchIcsrMessageHeader implements Serializable {

    private final static long serialVersionUID = 1L;

    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;

    @XmlElement(name="messagetype", required = true)
    protected String messageType;

    @XmlElement(name="messageformatversion", required = true)
    protected String messageFormatVersion;

    @XmlElement(name="messageformatrelease", required = true)
    protected String messageFormatRelease;

    @XmlElement(name="messagenumb", required = true)
    protected String messageNumb;

    @XmlElement(name="messagesenderidentifier", required = true)
    protected String messagesenderidentifier;

    @XmlElement(required = true, name="messagereceiveridentifier")
    protected String messagereceiveridentifier;

    @XmlElement(name="messagedateformat", required = true)
    protected String messageDateFormat;

    @XmlElement(name="messagedate", required = true)
    @XmlJavaTypeAdapter(IcsrR2DateAdapter.class)
    protected Date messageDate;

    /**
     * Gets the value of the lang property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the messagetype property.
     * 
     * @return possible object is {@link java.lang.String }
     * 
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messagetype property.
     * 
     * @param value allowed object is {@link java.lang.String }
     * 
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the messageformatversion property.
     * 
     * @return possible object is {@link java.lang.String }
     * 
     */
    public String getMessageFormatVersion() {
        return messageFormatVersion;
    }

    /**
     * Sets the value of the messageformatversion property.
     *
     * @param value allowed object is {@link java.lang.String }
     * 
     */
    public void setMessageFormatVersion(String value) {
        this.messageFormatVersion = value;
    }

    /**
     * Gets the value of the messageformatrelease property.
     * 
     * @return possible object is {@link java.lang.String }
     * 
     */
    public String getMessageFormatRelease() {
        return messageFormatRelease;
    }

    /**
     * Sets the value of the messageformatrelease property.
     *
     * @param value allowed object is {@link java.lang.String }
     * 
     */
    public void setMessageFormatRelease(String value) {
        this.messageFormatRelease = value;
    }

    /**
     * Gets the value of the messagenumb property.
     * 
     * @return possible object is {@link java.lang.String }
     * 
     */
    public String getMessageNumb() {
        return messageNumb;
    }

    /**
     * Sets the value of the messagenumb property.
     *
     * @param value allowed object is {@link java.lang.String }
     * 
     */
    public void setMessageNumb(String value) {
        this.messageNumb = value;
    }

    /**
     * Gets the value of the messagesenderidentifier property.
     * 
     * @return possible object is {@link java.lang.String }
     * 
     */
    public String getMessagesenderidentifier() {
        return messagesenderidentifier;
    }

    /**
     * Sets the value of the messagesenderidentifier property.
     *
     * @param value allowed object is {@link java.lang.String }
     * 
     */
    public void setMessagesenderidentifier(String value) {
        this.messagesenderidentifier = value;
    }

    /**
     * Gets the value of the messagereceiveridentifier property.
     * 
     * @return possible object is {@link java.lang.String }
     * 
     */
    public String getMessagereceiveridentifier() {
        return messagereceiveridentifier;
    }

    /**
     * Sets the value of the messagereceiveridentifier property.
     *
     * @param value allowed object is {@link java.lang.String }
     * 
     */
    public void setMessagereceiveridentifier(String value) {
        this.messagereceiveridentifier = value;
    }

    /**
     * Gets the value of the messagedateformat property.
     * 
     * @return possible object is {@link java.lang.String }
     * 
     */
    public String getMessageDateFormat() {
        return messageDateFormat;
    }

    /**
     * Sets the value of the messagedateformat property.
     *
     * @param value allowed object is {@link java.lang.String }
     * 
     */
    public void setMessageDateFormat(String value) {
        this.messageDateFormat = value;
    }

    /**
     * Gets the value of the messagedate property.
     * 
     * @return possible object is {@link java.lang.String }
     * 
     */
    public Date getMessageDate() {
        return messageDate;
    }

    /**
     * Sets the value of the messagedate property.
     *
     * @param value allowed object is {@link String }
     * 
     */
    public void setMessageDate(Date value) {
        this.messageDate = value;
    }

}
