//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 03:16:34 PM BST 
//

package eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.ack;

import eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.MessageIdentifier;
import eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.Messagedate;
import eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.Messagedateformat;
import eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.Messagenumb;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "icsrmessagenumb", "localmessagenumb", "icsrmessagesenderidentifier",
        "icsrmessagereceiveridentifier", "icsrmessagedateformat", "icsrmessagedate", "transmissionacknowledgmentcode",
        "parsingerrormessage" })
@XmlRootElement(name = "messageacknowledgment")
public class Messageacknowledgment implements Serializable {

    private final static long serialVersionUID = 1L;

    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;

    @XmlElement(required = true, name = "icsrmessagenumb")
    protected Messagenumb icsrmessagenumb;

    @XmlElement(name = "localmessagenumb")
    protected Messagenumb localmessagenumb;

    @XmlElement(required = true, name = "icsrmessagesenderidentifier")
    protected MessageIdentifier icsrmessagesenderidentifier;

    @XmlElement(required = true, name = "icsrmessagereceiveridentifier")
    protected MessageIdentifier icsrmessagereceiveridentifier;

    @XmlElement(required = true, name = "icsrmessagedateformat")
    protected Messagedateformat icsrmessagedateformat;

    @XmlElement(required = true, name = "icsrmessagedate")
    protected Messagedate icsrmessagedate;

    @XmlElement(required = true)
    protected Transmissionacknowledgmentcode transmissionacknowledgmentcode;

    protected Parsingerrormessage parsingerrormessage;

    /**
     * Gets the value of the lang property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the icsrmessagenumb property.
     * 
     * @return possible object is {@link Messagenumb }
     * 
     */
    public Messagenumb getIcsrmessagenumb() {
        return icsrmessagenumb;
    }

    /**
     * Sets the value of the icsrmessagenumb property.
     * 
     * @param value allowed object is {@link Messagenumb }
     * 
     */
    public void setIcsrmessagenumb(Messagenumb value) {
        this.icsrmessagenumb = value;
    }

    /**
     * Gets the value of the localmessagenumb property.
     * 
     * @return possible object is {@link Messagenumb }
     * 
     */
    public Messagenumb getLocalmessagenumb() {
        return localmessagenumb;
    }

    /**
     * Sets the value of the localmessagenumb property.
     * 
     * @param value allowed object is {@link Messagenumb }
     * 
     */
    public void setLocalmessagenumb(Messagenumb value) {
        this.localmessagenumb = value;
    }

    /**
     * Gets the value of the icsrmessagesenderidentifier property.
     * 
     * @return possible object is {@link MessageIdentifier }
     * 
     */
    public MessageIdentifier getIcsrmessagesenderidentifier() {
        return icsrmessagesenderidentifier;
    }

    /**
     * Sets the value of the icsrmessagesenderidentifier property.
     * 
     * @param value allowed object is {@link MessageIdentifier }
     * 
     */
    public void setIcsrmessagesenderidentifier(MessageIdentifier value) {
        this.icsrmessagesenderidentifier = value;
    }

    /**
     * Gets the value of the icsrmessagereceiveridentifier property.
     * 
     * @return possible object is {@link MessageIdentifier }
     * 
     */
    public MessageIdentifier getIcsrmessagereceiveridentifier() {
        return icsrmessagereceiveridentifier;
    }

    /**
     * Sets the value of the icsrmessagereceiveridentifier property.
     * 
     * @param value allowed object is {@link MessageIdentifier }
     * 
     */
    public void setIcsrmessagereceiveridentifier(MessageIdentifier value) {
        this.icsrmessagereceiveridentifier = value;
    }

    /**
     * Gets the value of the icsrmessagedateformat property.
     * 
     * @return possible object is {@link Messagedateformat }
     * 
     */
    public Messagedateformat getIcsrmessagedateformat() {
        return icsrmessagedateformat;
    }

    /**
     * Sets the value of the icsrmessagedateformat property.
     * 
     * @param value allowed object is {@link Messagedateformat }
     * 
     */
    public void setIcsrmessagedateformat(Messagedateformat value) {
        this.icsrmessagedateformat = value;
    }

    /**
     * Gets the value of the icsrmessagedate property.
     * 
     * @return possible object is {@link Messagedate }
     * 
     */
    public Messagedate getIcsrmessagedate() {
        return icsrmessagedate;
    }

    /**
     * Sets the value of the icsrmessagedate property.
     * 
     * @param value allowed object is {@link Messagedate }
     * 
     */
    public void setIcsrmessagedate(Messagedate value) {
        this.icsrmessagedate = value;
    }

    /**
     * Gets the value of the transmissionacknowledgmentcode property.
     * 
     * @return possible object is {@link Transmissionacknowledgmentcode }
     * 
     */
    public Transmissionacknowledgmentcode getTransmissionacknowledgmentcode() {
        return transmissionacknowledgmentcode;
    }

    /**
     * Sets the value of the transmissionacknowledgmentcode property.
     * 
     * @param value allowed object is {@link Transmissionacknowledgmentcode }
     * 
     */
    public void setTransmissionacknowledgmentcode(Transmissionacknowledgmentcode value) {
        this.transmissionacknowledgmentcode = value;
    }

    /**
     * Gets the value of the parsingerrormessage property.
     * 
     * @return possible object is {@link eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.ack.Parsingerrormessage }
     * 
     */
    public Parsingerrormessage getParsingerrormessage() {
        return parsingerrormessage;
    }

    /**
     * Sets the value of the parsingerrormessage property.
     * 
     * @param value allowed object is {@link eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.ack.Parsingerrormessage }
     * 
     */
    public void setParsingerrormessage(Parsingerrormessage value) {
        this.parsingerrormessage = value;
    }

}
