//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 03:16:34 PM BST 
//

package eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.ack;

import eu.europa.ema.phv.common.xmladapter.IcsrR2DateAdapter;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.util.Date;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "messageacknowledgment")
public class Messageacknowledgment implements Serializable {

    private final static long serialVersionUID = 1L;

    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;

    @XmlElement(required = true, name = "icsrmessagenumb")
    protected String icsrmessagenumb;

    @XmlElement(name = "localmessagenumb")
    protected String localmessagenumb;

    @XmlElement(required = true, name = "icsrmessagesenderidentifier")
    protected String icsrmessagesenderidentifier;

    @XmlElement(required = true, name = "icsrmessagereceiveridentifier")
    protected String icsrmessagereceiveridentifier;

    @XmlElement(required = true, name = "icsrmessagedateformat")
    protected String icsrmessagedateformat;

    @XmlElement(required = true, name = "icsrmessagedate")
    @XmlJavaTypeAdapter(IcsrR2DateAdapter.class)
    protected Date icsrmessagedate;

    @XmlElement(required = true)
    protected String transmissionacknowledgmentcode;

    @XmlElement(name = "parsingerrormessage")
    protected String parsingerrormessage;

    /**
     * Gets the value of the lang property.
     *
     * @return possible object is {@link String }
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     *
     * @param value allowed object is {@link String }
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the icsrmessagenumb property.
     *
     * @return possible object is {@link java.lang.String }
     */
    public String getIcsrmessagenumb() {
        return icsrmessagenumb;
    }

    /**
     * Sets the value of the icsrmessagenumb property.
     *
     * @param value allowed object is {@link java.lang.String }
     */
    public void setIcsrmessagenumb(String value) {
        this.icsrmessagenumb = value;
    }

    /**
     * Gets the value of the localmessagenumb property.
     *
     * @return possible object is {@link java.lang.String }
     */
    public String getLocalmessagenumb() {
        return localmessagenumb;
    }

    /**
     * Sets the value of the localmessagenumb property.
     *
     * @param value allowed object is {@link java.lang.String }
     */
    public void setLocalmessagenumb(String value) {
        this.localmessagenumb = value;
    }

    /**
     * Gets the value of the icsrmessagesenderidentifier property.
     *
     * @return possible object is {@link java.lang.String }
     */
    public String getIcsrmessagesenderidentifier() {
        return icsrmessagesenderidentifier;
    }

    /**
     * Sets the value of the icsrmessagesenderidentifier property.
     *
     * @param value allowed object is {@link java.lang.String }
     */
    public void setIcsrmessagesenderidentifier(String value) {
        this.icsrmessagesenderidentifier = value;
    }

    /**
     * Gets the value of the icsrmessagereceiveridentifier property.
     *
     * @return possible object is {@link java.lang.String }
     */
    public String getIcsrmessagereceiveridentifier() {
        return icsrmessagereceiveridentifier;
    }

    /**
     * Sets the value of the icsrmessagereceiveridentifier property.
     *
     * @param value allowed object is {@link java.lang.String }
     */
    public void setIcsrmessagereceiveridentifier(String value) {
        this.icsrmessagereceiveridentifier = value;
    }

    /**
     * Gets the value of the icsrmessagedateformat property.
     *
     * @return possible object is {@link java.lang.String }
     */
    public String getIcsrmessagedateformat() {
        return icsrmessagedateformat;
    }

    /**
     * Sets the value of the icsrmessagedateformat property.
     *
     * @param value allowed object is {@link java.lang.String }
     */
    public void setIcsrmessagedateformat(String value) {
        this.icsrmessagedateformat = value;
    }

    /**
     * Gets the value of the icsrmessagedate property.
     *
     * @return possible object is {@link java.lang.String }
     */
    public Date getIcsrmessagedate() {
        return icsrmessagedate;
    }

    /**
     * Sets the value of the icsrmessagedate property.
     *
     * @param value allowed object is {@link java.lang.String }
     */
    public void setIcsrmessagedate(Date value) {
        this.icsrmessagedate = value;
    }

    /**
     * Gets the value of the transmissionacknowledgmentcode property.
     *
     * @return possible object is {@link java.lang.String }
     */
    public String getTransmissionacknowledgmentcode() {
        return transmissionacknowledgmentcode;
    }

    /**
     * Sets the value of the transmissionacknowledgmentcode property.
     *
     * @param value allowed object is {@link java.lang.String }
     */
    public void setTransmissionacknowledgmentcode(String value) {
        this.transmissionacknowledgmentcode = value;
    }

    /**
     * Gets the value of the parsingerrormessage property.
     *
     * @return possible object is {@link java.lang.String }
     */
    public String getParsingerrormessage() {
        return parsingerrormessage;
    }

    /**
     * Sets the value of the parsingerrormessage property.
     *
     * @param value allowed object is {@link java.lang.String }
     */
    public void setParsingerrormessage(String value) {
        this.parsingerrormessage = value;
    }

}
