//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 03:16:34 PM BST 
//

package eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.ack;

import eu.europa.ema.phv.common.xmladapter.IcsrR2DateAdapter;
import org.eclipse.persistence.oxm.annotations.XmlPath;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.util.Date;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "reportacknowledgment")
public class ReportAcknowledgment implements Serializable {

    private final static long serialVersionUID = 1L;

    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;

    @XmlPath("reportacknowledgment/safetyreportversion/text()")
    private String safetyreportversion;

    @XmlPath("reportacknowledgment/safetyreportid/text()")
    private String safetyreportid;

    @XmlPath("reportacknowledgment/localreportnumb/text()")
    private String localreportnumb;

    @XmlPath("reportacknowledgment/authoritynumb/text()")
    private String authoritynumb;

    @XmlPath("reportacknowledgment/companynumb/text()")
    private String companynumb;

    @XmlPath("reportacknowledgment/receiptdateformat/text()")
    private String receiptdateformat;

    @XmlPath("reportacknowledgment/receiptdate/text()")
    @XmlJavaTypeAdapter(IcsrR2DateAdapter.class)
    private Date receiptdate;

    @XmlPath("reportacknowledgment/reportacknowledgmentcode/text()")
    private String reportacknowledgmentcode;

    @XmlPath("reportacknowledgment/errormessagecomment/text()")
    private String errormessagecomment;

    /**
     * Gets the value of the lang property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLang(String value) {
        this.lang = value;
    }

    public String getSafetyreportversion() {
        return safetyreportversion;
    }

    public void setSafetyreportversion(String safetyreportversion) {
        this.safetyreportversion = safetyreportversion;
    }

    public String getSafetyreportid() {
        return safetyreportid;
    }

    public void setSafetyreportid(String safetyreportid) {
        this.safetyreportid = safetyreportid;
    }

    public String getLocalreportnumb() {
        return localreportnumb;
    }

    public void setLocalreportnumb(String localreportnumb) {
        this.localreportnumb = localreportnumb;
    }

    public String getAuthoritynumb() {
        return authoritynumb;
    }

    public void setAuthoritynumb(String authoritynumb) {
        this.authoritynumb = authoritynumb;
    }

    public String getCompanynumb() {
        return companynumb;
    }

    public void setCompanynumb(String companynumb) {
        this.companynumb = companynumb;
    }

    public String getReceiptdateformat() {
        return receiptdateformat;
    }

    public void setReceiptdateformat(String receiptdateformat) {
        this.receiptdateformat = receiptdateformat;
    }

    public Date getReceiptdate() {
        return receiptdate;
    }

    public void setReceiptdate(Date receiptdate) {
        this.receiptdate = receiptdate;
    }

    public String getReportacknowledgmentcode() {
        return reportacknowledgmentcode;
    }

    public void setReportacknowledgmentcode(String reportacknowledgmentcode) {
        this.reportacknowledgmentcode = reportacknowledgmentcode;
    }

    public String getErrormessagecomment() {
        return errormessagecomment;
    }

    public void setErrormessagecomment(String errormessagecomment) {
        this.errormessagecomment = errormessagecomment;
    }
}
