//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 01:13:21 PM BST 
//


package eu.europa.ema.phv.common.model.adrhuman.icsrr2.ack;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.ema.phv.common.model.adrhuman.icsrr2.ack package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.ema.phv.common.model.adrhuman.icsrr2.ack
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Reportacknowledgment }
     * 
     */
    public Reportacknowledgment createReportacknowledgment() {
        return new Reportacknowledgment();
    }

    /**
     * Create an instance of {@link Safetyreportversion }
     * 
     */
    public Safetyreportversion createSafetyreportversion() {
        return new Safetyreportversion();
    }

    /**
     * Create an instance of {@link Safetyreportid }
     * 
     */
    public Safetyreportid createSafetyreportid() {
        return new Safetyreportid();
    }

    /**
     * Create an instance of {@link Localreportnumb }
     * 
     */
    public Localreportnumb createLocalreportnumb() {
        return new Localreportnumb();
    }

    /**
     * Create an instance of {@link Authoritynumb }
     * 
     */
    public Authoritynumb createAuthoritynumb() {
        return new Authoritynumb();
    }

    /**
     * Create an instance of {@link Companynumb }
     * 
     */
    public Companynumb createCompanynumb() {
        return new Companynumb();
    }

    /**
     * Create an instance of {@link Receiptdateformat }
     * 
     */
    public Receiptdateformat createReceiptdateformat() {
        return new Receiptdateformat();
    }

    /**
     * Create an instance of {@link Receiptdate }
     * 
     */
    public Receiptdate createReceiptdate() {
        return new Receiptdate();
    }

    /**
     * Create an instance of {@link Reportacknowledgmentcode }
     * 
     */
    public Reportacknowledgmentcode createReportacknowledgmentcode() {
        return new Reportacknowledgmentcode();
    }

    /**
     * Create an instance of {@link Errormessagecomment }
     * 
     */
    public Errormessagecomment createErrormessagecomment() {
        return new Errormessagecomment();
    }

    /**
     * Create an instance of {@link Icsrmessagereceiveridentifier }
     * 
     */
    public Icsrmessagereceiveridentifier createIcsrmessagereceiveridentifier() {
        return new Icsrmessagereceiveridentifier();
    }

    /**
     * Create an instance of {@link Icsrmessagedate }
     * 
     */
    public Icsrmessagedate createIcsrmessagedate() {
        return new Icsrmessagedate();
    }

    /**
     * Create an instance of {@link Messagetype }
     * 
     */
    public Messagetype createMessagetype() {
        return new Messagetype();
    }

    /**
     * Create an instance of {@link Transmissionacknowledgmentcode }
     * 
     */
    public Transmissionacknowledgmentcode createTransmissionacknowledgmentcode() {
        return new Transmissionacknowledgmentcode();
    }

    /**
     * Create an instance of {@link Messageformatversion }
     * 
     */
    public Messageformatversion createMessageformatversion() {
        return new Messageformatversion();
    }

    /**
     * Create an instance of {@link Icsrmessagesenderidentifier }
     * 
     */
    public Icsrmessagesenderidentifier createIcsrmessagesenderidentifier() {
        return new Icsrmessagesenderidentifier();
    }

    /**
     * Create an instance of {@link Parsingerrormessage }
     * 
     */
    public Parsingerrormessage createParsingerrormessage() {
        return new Parsingerrormessage();
    }

    /**
     * Create an instance of {@link Localmessagenumb }
     * 
     */
    public Localmessagenumb createLocalmessagenumb() {
        return new Localmessagenumb();
    }

    /**
     * Create an instance of {@link Messagenumb }
     * 
     */
    public Messagenumb createMessagenumb() {
        return new Messagenumb();
    }

    /**
     * Create an instance of {@link Messageformatrelease }
     * 
     */
    public Messageformatrelease createMessageformatrelease() {
        return new Messageformatrelease();
    }

    /**
     * Create an instance of {@link Messageacknowledgment }
     * 
     */
    public Messageacknowledgment createMessageacknowledgment() {
        return new Messageacknowledgment();
    }

    /**
     * Create an instance of {@link Icsrmessagenumb }
     * 
     */
    public Icsrmessagenumb createIcsrmessagenumb() {
        return new Icsrmessagenumb();
    }

    /**
     * Create an instance of {@link Icsrmessagedateformat }
     * 
     */
    public Icsrmessagedateformat createIcsrmessagedateformat() {
        return new Icsrmessagedateformat();
    }

    /**
     * Create an instance of {@link Acknowledgment }
     * 
     */
    public Acknowledgment createAcknowledgment() {
        return new Acknowledgment();
    }

    /**
     * Create an instance of {@link Ichicsrmessageheader }
     * 
     */
    public Ichicsrmessageheader createIchicsrmessageheader() {
        return new Ichicsrmessageheader();
    }

    /**
     * Create an instance of {@link Messagesenderidentifier }
     * 
     */
    public Messagesenderidentifier createMessagesenderidentifier() {
        return new Messagesenderidentifier();
    }

    /**
     * Create an instance of {@link Messagereceiveridentifier }
     * 
     */
    public Messagereceiveridentifier createMessagereceiveridentifier() {
        return new Messagereceiveridentifier();
    }

    /**
     * Create an instance of {@link Messagedateformat }
     * 
     */
    public Messagedateformat createMessagedateformat() {
        return new Messagedateformat();
    }

    /**
     * Create an instance of {@link Messagedate }
     * 
     */
    public Messagedate createMessagedate() {
        return new Messagedate();
    }

    /**
     * Create an instance of {@link Ichicsrack }
     * 
     */
    public Ichicsrack createIchicsrack() {
        return new Ichicsrack();
    }

}
