//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 01:13:21 PM BST 
//


package eu.europa.ema.phv.common.model.adrhuman.icsrr2.ack;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment"
})
@XmlRootElement(name = "reportacknowledgment")
public class Reportacknowledgment {

    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;
    @XmlElements({
        @XmlElement(name = "safetyreportversion", type = Safetyreportversion.class),
        @XmlElement(name = "safetyreportid", type = Safetyreportid.class),
        @XmlElement(name = "localreportnumb", type = Localreportnumb.class),
        @XmlElement(name = "authoritynumb", type = Authoritynumb.class),
        @XmlElement(name = "companynumb", type = Companynumb.class),
        @XmlElement(name = "receiptdateformat", type = Receiptdateformat.class),
        @XmlElement(name = "receiptdate", type = Receiptdate.class),
        @XmlElement(name = "reportacknowledgmentcode", type = Reportacknowledgmentcode.class),
        @XmlElement(name = "errormessagecomment", type = Errormessagecomment.class)
    })
    protected List<Object> safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment;

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSafetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Safetyreportversion }
     * {@link Safetyreportid }
     * {@link Localreportnumb }
     * {@link Authoritynumb }
     * {@link Companynumb }
     * {@link Receiptdateformat }
     * {@link Receiptdate }
     * {@link Reportacknowledgmentcode }
     * {@link Errormessagecomment }
     * 
     * 
     */
    public List<Object> getSafetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment() {
        if (safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment == null) {
            safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment = new ArrayList<Object>();
        }
        return this.safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment;
    }

}
