//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 05:38:27 PM BST 
//


package eu.europa.ema.phv.common.model.adrhuman.icsrr2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testdateformat",
    "testdate",
    "testname",
    "testresult",
    "testunit",
    "lowtestrange",
    "hightestrange",
    "moreinformation"
})
@XmlRootElement(name = "test")
public class Test
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;
    protected Testdateformat testdateformat;
    protected Testdate testdate;
    protected Testname testname;
    protected Testresult testresult;
    protected Testunit testunit;
    protected Lowtestrange lowtestrange;
    protected Hightestrange hightestrange;
    protected Moreinformation moreinformation;

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the testdateformat property.
     * 
     * @return
     *     possible object is
     *     {@link Testdateformat }
     *     
     */
    public Testdateformat getTestdateformat() {
        return testdateformat;
    }

    /**
     * Sets the value of the testdateformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testdateformat }
     *     
     */
    public void setTestdateformat(Testdateformat value) {
        this.testdateformat = value;
    }

    /**
     * Gets the value of the testdate property.
     * 
     * @return
     *     possible object is
     *     {@link Testdate }
     *     
     */
    public Testdate getTestdate() {
        return testdate;
    }

    /**
     * Sets the value of the testdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testdate }
     *     
     */
    public void setTestdate(Testdate value) {
        this.testdate = value;
    }

    /**
     * Gets the value of the testname property.
     * 
     * @return
     *     possible object is
     *     {@link Testname }
     *     
     */
    public Testname getTestname() {
        return testname;
    }

    /**
     * Sets the value of the testname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testname }
     *     
     */
    public void setTestname(Testname value) {
        this.testname = value;
    }

    /**
     * Gets the value of the testresult property.
     * 
     * @return
     *     possible object is
     *     {@link Testresult }
     *     
     */
    public Testresult getTestresult() {
        return testresult;
    }

    /**
     * Sets the value of the testresult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testresult }
     *     
     */
    public void setTestresult(Testresult value) {
        this.testresult = value;
    }

    /**
     * Gets the value of the testunit property.
     * 
     * @return
     *     possible object is
     *     {@link Testunit }
     *     
     */
    public Testunit getTestunit() {
        return testunit;
    }

    /**
     * Sets the value of the testunit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testunit }
     *     
     */
    public void setTestunit(Testunit value) {
        this.testunit = value;
    }

    /**
     * Gets the value of the lowtestrange property.
     * 
     * @return
     *     possible object is
     *     {@link Lowtestrange }
     *     
     */
    public Lowtestrange getLowtestrange() {
        return lowtestrange;
    }

    /**
     * Sets the value of the lowtestrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lowtestrange }
     *     
     */
    public void setLowtestrange(Lowtestrange value) {
        this.lowtestrange = value;
    }

    /**
     * Gets the value of the hightestrange property.
     * 
     * @return
     *     possible object is
     *     {@link Hightestrange }
     *     
     */
    public Hightestrange getHightestrange() {
        return hightestrange;
    }

    /**
     * Sets the value of the hightestrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hightestrange }
     *     
     */
    public void setHightestrange(Hightestrange value) {
        this.hightestrange = value;
    }

    /**
     * Gets the value of the moreinformation property.
     * 
     * @return
     *     possible object is
     *     {@link Moreinformation }
     *     
     */
    public Moreinformation getMoreinformation() {
        return moreinformation;
    }

    /**
     * Sets the value of the moreinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Moreinformation }
     *     
     */
    public void setMoreinformation(Moreinformation value) {
        this.moreinformation = value;
    }

}
