//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 03:16:34 PM BST 
//

package eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.ack;

import eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.Ichicsrmessageheader;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "ichicsrmessageheader", "acknowledgment" })
@XmlRootElement(name = "ichicsrack")
public class Ichicsrack implements Serializable {

    private final static long serialVersionUID = 1L;

    @XmlAttribute(name = "lang", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;

    @XmlElement(required = true)
    protected Ichicsrmessageheader ichicsrmessageheader;

    @XmlElement(required = true)
    protected Acknowledgment acknowledgment;

    /**
     * Gets the value of the lang property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the ichicsrmessageheader property.
     * 
     * @return possible object is {@link Ichicsrmessageheader }
     * 
     */
    public Ichicsrmessageheader getIchicsrmessageheader() {
        return ichicsrmessageheader;
    }

    /**
     * Sets the value of the ichicsrmessageheader property.
     * 
     * @param value allowed object is {@link Ichicsrmessageheader }
     * 
     */
    public void setIchicsrmessageheader(Ichicsrmessageheader value) {
        this.ichicsrmessageheader = value;
    }

    /**
     * Gets the value of the acknowledgment property.
     * 
     * @return possible object is {@link Acknowledgment }
     * 
     */
    public Acknowledgment getAcknowledgment() {
        return acknowledgment;
    }

    /**
     * Sets the value of the acknowledgment property.
     * 
     * @param value allowed object is {@link Acknowledgment }
     * 
     */
    public void setAcknowledgment(Acknowledgment value) {
        this.acknowledgment = value;
    }

}
