//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 03:16:34 PM BST 
//

package eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml.ack;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment" })
@XmlRootElement(name = "reportacknowledgment")
public class Reportacknowledgment implements Serializable {

    private final static long serialVersionUID = 1L;

    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;

    @XmlElements({ @XmlElement(name = "safetyreportversion", type = Safetyreportversion.class),
            @XmlElement(name = "safetyreportid", type = Safetyreportid.class),
            @XmlElement(name = "localreportnumb", type = Localreportnumb.class),
            @XmlElement(name = "authoritynumb", type = Authoritynumb.class),
            @XmlElement(name = "companynumb", type = Companynumb.class),
            @XmlElement(name = "receiptdateformat", type = Receiptdateformat.class),
            @XmlElement(name = "receiptdate", type = Receiptdate.class),
            @XmlElement(name = "reportacknowledgmentcode", type = Reportacknowledgmentcode.class),
            @XmlElement(name = "errormessagecomment", type = Errormessagecomment.class) })
    protected List<Serializable> safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment;

    /**
     * Gets the value of the lang property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the
     * safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment
     * property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the
     * safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment
     * property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSafetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment()
     *         .add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Safetyreportversion } {@link Safetyreportid }
     * {@link Localreportnumb } {@link Authoritynumb } {@link Companynumb }
     * {@link Receiptdateformat } {@link Receiptdate }
     * {@link Reportacknowledgmentcode } {@link Errormessagecomment }
     * 
     * 
     */
    public List<Serializable> getSafetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment() {
        if (safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment == null) {
            safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment = new ArrayList<Serializable>();
        }
        return this.safetyreportversionOrSafetyreportidOrLocalreportnumbOrAuthoritynumbOrCompanynumbOrReceiptdateformatOrReceiptdateOrReportacknowledgmentcodeOrErrormessagecomment;
    }

}
