//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 01:32:03 PM BST 
//


package eu.europa.ema.phv.common.model.adrhuman.icsrr2.master;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "localnumber"
})
@XmlRootElement(name = "clusterduplicate")
public class Clusterduplicate {

    @XmlElement(required = true)
    protected Localnumber localnumber;

    /**
     * Gets the value of the localnumber property.
     * 
     * @return
     *     possible object is
     *     {@link Localnumber }
     *     
     */
    public Localnumber getLocalnumber() {
        return localnumber;
    }

    /**
     * Sets the value of the localnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Localnumber }
     *     
     */
    public void setLocalnumber(Localnumber value) {
        this.localnumber = value;
    }

}
