//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 05:38:27 PM BST 
//

package eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml;

import javax.xml.bind.annotation.*;
import java.io.Serializable;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "localnumber" })
@XmlRootElement(name = "clusterduplicate")
public class Clusterduplicate implements Serializable {

    private final static long serialVersionUID = 1L;

    @XmlElement(required = true)
    protected Localnumber localnumber;

    /**
     * Gets the value of the localnumber property.
     * 
     * @return possible object is {@link Localnumber }
     * 
     */
    public Localnumber getLocalnumber() {
        return localnumber;
    }

    /**
     * Sets the value of the localnumber property.
     * 
     * @param value allowed object is {@link Localnumber }
     * 
     */
    public void setLocalnumber(Localnumber value) {
        this.localnumber = value;
    }

}
