//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 05:38:27 PM BST 
//

package eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "patientepisodenamemeddraversion", "patientepisodename",
        "patientmedicalstartdateformat", "patientmedicalstartdate", "patientmedicalcontinue",
        "patientmedicalenddateformat", "patientmedicalenddate", "patientmedicalcomment" })
@XmlRootElement(name = "medicalhistoryepisode")
public class Medicalhistoryepisode implements Serializable {

    private final static long serialVersionUID = 1L;

    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;

    protected Patientepisodenamemeddraversion patientepisodenamemeddraversion;

    protected Patientepisodename patientepisodename;

    protected Patientmedicalstartdateformat patientmedicalstartdateformat;

    protected Patientmedicalstartdate patientmedicalstartdate;

    protected Patientmedicalcontinue patientmedicalcontinue;

    protected Patientmedicalenddateformat patientmedicalenddateformat;

    protected Patientmedicalenddate patientmedicalenddate;

    protected Patientmedicalcomment patientmedicalcomment;

    /**
     * Gets the value of the lang property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the patientepisodenamemeddraversion property.
     * 
     * @return possible object is {@link Patientepisodenamemeddraversion }
     * 
     */
    public Patientepisodenamemeddraversion getPatientepisodenamemeddraversion() {
        return patientepisodenamemeddraversion;
    }

    /**
     * Sets the value of the patientepisodenamemeddraversion property.
     * 
     * @param value allowed object is {@link Patientepisodenamemeddraversion }
     * 
     */
    public void setPatientepisodenamemeddraversion(Patientepisodenamemeddraversion value) {
        this.patientepisodenamemeddraversion = value;
    }

    /**
     * Gets the value of the patientepisodename property.
     * 
     * @return possible object is {@link Patientepisodename }
     * 
     */
    public Patientepisodename getPatientepisodename() {
        return patientepisodename;
    }

    /**
     * Sets the value of the patientepisodename property.
     * 
     * @param value allowed object is {@link Patientepisodename }
     * 
     */
    public void setPatientepisodename(Patientepisodename value) {
        this.patientepisodename = value;
    }

    /**
     * Gets the value of the patientmedicalstartdateformat property.
     * 
     * @return possible object is {@link Patientmedicalstartdateformat }
     * 
     */
    public Patientmedicalstartdateformat getPatientmedicalstartdateformat() {
        return patientmedicalstartdateformat;
    }

    /**
     * Sets the value of the patientmedicalstartdateformat property.
     * 
     * @param value allowed object is {@link Patientmedicalstartdateformat }
     * 
     */
    public void setPatientmedicalstartdateformat(Patientmedicalstartdateformat value) {
        this.patientmedicalstartdateformat = value;
    }

    /**
     * Gets the value of the patientmedicalstartdate property.
     * 
     * @return possible object is {@link Patientmedicalstartdate }
     * 
     */
    public Patientmedicalstartdate getPatientmedicalstartdate() {
        return patientmedicalstartdate;
    }

    /**
     * Sets the value of the patientmedicalstartdate property.
     * 
     * @param value allowed object is {@link Patientmedicalstartdate }
     * 
     */
    public void setPatientmedicalstartdate(Patientmedicalstartdate value) {
        this.patientmedicalstartdate = value;
    }

    /**
     * Gets the value of the patientmedicalcontinue property.
     * 
     * @return possible object is {@link Patientmedicalcontinue }
     * 
     */
    public Patientmedicalcontinue getPatientmedicalcontinue() {
        return patientmedicalcontinue;
    }

    /**
     * Sets the value of the patientmedicalcontinue property.
     * 
     * @param value allowed object is {@link Patientmedicalcontinue }
     * 
     */
    public void setPatientmedicalcontinue(Patientmedicalcontinue value) {
        this.patientmedicalcontinue = value;
    }

    /**
     * Gets the value of the patientmedicalenddateformat property.
     * 
     * @return possible object is {@link Patientmedicalenddateformat }
     * 
     */
    public Patientmedicalenddateformat getPatientmedicalenddateformat() {
        return patientmedicalenddateformat;
    }

    /**
     * Sets the value of the patientmedicalenddateformat property.
     * 
     * @param value allowed object is {@link Patientmedicalenddateformat }
     * 
     */
    public void setPatientmedicalenddateformat(Patientmedicalenddateformat value) {
        this.patientmedicalenddateformat = value;
    }

    /**
     * Gets the value of the patientmedicalenddate property.
     * 
     * @return possible object is {@link Patientmedicalenddate }
     * 
     */
    public Patientmedicalenddate getPatientmedicalenddate() {
        return patientmedicalenddate;
    }

    /**
     * Sets the value of the patientmedicalenddate property.
     * 
     * @param value allowed object is {@link Patientmedicalenddate }
     * 
     */
    public void setPatientmedicalenddate(Patientmedicalenddate value) {
        this.patientmedicalenddate = value;
    }

    /**
     * Gets the value of the patientmedicalcomment property.
     * 
     * @return possible object is {@link Patientmedicalcomment }
     * 
     */
    public Patientmedicalcomment getPatientmedicalcomment() {
        return patientmedicalcomment;
    }

    /**
     * Sets the value of the patientmedicalcomment property.
     * 
     * @param value allowed object is {@link Patientmedicalcomment }
     * 
     */
    public void setPatientmedicalcomment(Patientmedicalcomment value) {
        this.patientmedicalcomment = value;
    }

}
