//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.20 at 05:38:27 PM BST 
//

package eu.europa.ema.phv.common.model.adrhuman.icsrr2.xml;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "patientdrugname", "patientdrugstartdateformat", "patientdrugstartdate",
        "patientdrugenddateformat", "patientdrugenddate", "patientindicationmeddraversion", "patientdrugindication",
        "patientdrgreactionmeddraversion", "patientdrugreaction" })
@XmlRootElement(name = "patientpastdrugtherapy")
public class Patientpastdrugtherapy implements Serializable {

    private final static long serialVersionUID = 1L;

    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String lang;

    protected Patientdrugname patientdrugname;

    protected Patientdrugstartdateformat patientdrugstartdateformat;

    protected Patientdrugstartdate patientdrugstartdate;

    protected Patientdrugenddateformat patientdrugenddateformat;

    protected Patientdrugenddate patientdrugenddate;

    protected Patientindicationmeddraversion patientindicationmeddraversion;

    protected Patientdrugindication patientdrugindication;

    protected Patientdrgreactionmeddraversion patientdrgreactionmeddraversion;

    protected Patientdrugreaction patientdrugreaction;

    /**
     * Gets the value of the lang property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the patientdrugname property.
     * 
     * @return possible object is {@link Patientdrugname }
     * 
     */
    public Patientdrugname getPatientdrugname() {
        return patientdrugname;
    }

    /**
     * Sets the value of the patientdrugname property.
     * 
     * @param value allowed object is {@link Patientdrugname }
     * 
     */
    public void setPatientdrugname(Patientdrugname value) {
        this.patientdrugname = value;
    }

    /**
     * Gets the value of the patientdrugstartdateformat property.
     * 
     * @return possible object is {@link Patientdrugstartdateformat }
     * 
     */
    public Patientdrugstartdateformat getPatientdrugstartdateformat() {
        return patientdrugstartdateformat;
    }

    /**
     * Sets the value of the patientdrugstartdateformat property.
     * 
     * @param value allowed object is {@link Patientdrugstartdateformat }
     * 
     */
    public void setPatientdrugstartdateformat(Patientdrugstartdateformat value) {
        this.patientdrugstartdateformat = value;
    }

    /**
     * Gets the value of the patientdrugstartdate property.
     * 
     * @return possible object is {@link Patientdrugstartdate }
     * 
     */
    public Patientdrugstartdate getPatientdrugstartdate() {
        return patientdrugstartdate;
    }

    /**
     * Sets the value of the patientdrugstartdate property.
     * 
     * @param value allowed object is {@link Patientdrugstartdate }
     * 
     */
    public void setPatientdrugstartdate(Patientdrugstartdate value) {
        this.patientdrugstartdate = value;
    }

    /**
     * Gets the value of the patientdrugenddateformat property.
     * 
     * @return possible object is {@link Patientdrugenddateformat }
     * 
     */
    public Patientdrugenddateformat getPatientdrugenddateformat() {
        return patientdrugenddateformat;
    }

    /**
     * Sets the value of the patientdrugenddateformat property.
     * 
     * @param value allowed object is {@link Patientdrugenddateformat }
     * 
     */
    public void setPatientdrugenddateformat(Patientdrugenddateformat value) {
        this.patientdrugenddateformat = value;
    }

    /**
     * Gets the value of the patientdrugenddate property.
     * 
     * @return possible object is {@link Patientdrugenddate }
     * 
     */
    public Patientdrugenddate getPatientdrugenddate() {
        return patientdrugenddate;
    }

    /**
     * Sets the value of the patientdrugenddate property.
     * 
     * @param value allowed object is {@link Patientdrugenddate }
     * 
     */
    public void setPatientdrugenddate(Patientdrugenddate value) {
        this.patientdrugenddate = value;
    }

    /**
     * Gets the value of the patientindicationmeddraversion property.
     * 
     * @return possible object is {@link Patientindicationmeddraversion }
     * 
     */
    public Patientindicationmeddraversion getPatientindicationmeddraversion() {
        return patientindicationmeddraversion;
    }

    /**
     * Sets the value of the patientindicationmeddraversion property.
     * 
     * @param value allowed object is {@link Patientindicationmeddraversion }
     * 
     */
    public void setPatientindicationmeddraversion(Patientindicationmeddraversion value) {
        this.patientindicationmeddraversion = value;
    }

    /**
     * Gets the value of the patientdrugindication property.
     * 
     * @return possible object is {@link Patientdrugindication }
     * 
     */
    public Patientdrugindication getPatientdrugindication() {
        return patientdrugindication;
    }

    /**
     * Sets the value of the patientdrugindication property.
     * 
     * @param value allowed object is {@link Patientdrugindication }
     * 
     */
    public void setPatientdrugindication(Patientdrugindication value) {
        this.patientdrugindication = value;
    }

    /**
     * Gets the value of the patientdrgreactionmeddraversion property.
     * 
     * @return possible object is {@link Patientdrgreactionmeddraversion }
     * 
     */
    public Patientdrgreactionmeddraversion getPatientdrgreactionmeddraversion() {
        return patientdrgreactionmeddraversion;
    }

    /**
     * Sets the value of the patientdrgreactionmeddraversion property.
     * 
     * @param value allowed object is {@link Patientdrgreactionmeddraversion }
     * 
     */
    public void setPatientdrgreactionmeddraversion(Patientdrgreactionmeddraversion value) {
        this.patientdrgreactionmeddraversion = value;
    }

    /**
     * Gets the value of the patientdrugreaction property.
     * 
     * @return possible object is {@link Patientdrugreaction }
     * 
     */
    public Patientdrugreaction getPatientdrugreaction() {
        return patientdrugreaction;
    }

    /**
     * Sets the value of the patientdrugreaction property.
     * 
     * @param value allowed object is {@link Patientdrugreaction }
     * 
     */
    public void setPatientdrugreaction(Patientdrugreaction value) {
        this.patientdrugreaction = value;
    }

}
